Lambda-School-Labs/labs9-map-scratcher

backend/.gitignore, frontend/components/Map/Blank.js, frontend/components/Map/Map.js, frontend/package.json, frontend/pages/index.js, frontend/pages/map.js, frontend/yarn.lock
Setting up the basics of the leaflet map. Not a currently working solution, but needs to be merged to get more eyes on the issue. 
react-leaflet is not enjoying playing well with next.js. I currently have it rendered as a dynamic component with no SSR to circumvent a previous issue, but it is not displaying correctly. 
=> starting to set up map

.gitignore, backend/package.json, frontend/package.json, frontend/yarn.lock
Breaking bug fixes
Testing the scripts (`yarn dev`)
=> Fix comma error, remove similar script

backend/resolvers/User.js, backend/resolvers/index.js
User resolver complete besides visit
- [x ] I have made corresponding changes to the documentation
- [ x] There are no merge conflicts
=> User resolver

.prettierrc
Adds prettier preferences for standardized styling
=> Added preferences for prettier

README.md, backend/prisma/datamodel.prisma, backend/prisma/generated/prisma-client/index.d.ts, backend/prisma/generated/prisma-client/prisma-schema.js, backend/resolvers/Country.js, backend/resolvers/Mutation.js, backend/resolvers/Query.js, backend/resolvers/index.js, backend/schema.graphql, frontend/package.json, frontend/yarn.lock
The data model was requiring fields that it should not have been requiring, which was causing sensible mutations to fail. As long as the data model was being updated, I also added a relation between country and visits to make it easier to get all visits for a given country (and wrote that resolver)
I ran the queries and mutation myself in the graphQL playground and verified that the field was no longer required and that the mutation or query succeeded.
=> Update Prisma data model and GraphQL schema

README.md
=> update front-end link

.travis.yml, frontend/package.json, frontend/yarn.lock
I'm not sure how I exactly test this .travis.yml without having to merge it with master, so this will be a work-in-progress once it gets merged. Make sure to remove Grommet and Styled-Components inside your local dependencies so you don't accidentally push it and merge it later.
=> Implement Travis CI, remove Grommet+Styled Components

frontend/components/Map/Map.js, frontend/pages/map.js
Fixed Leaflet component styles so there are no more unrendered tiles.
https://trello.com/c/3dVRyG61/53-fix-map-rendering-visibility
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Fixed map component visibility

backend/prisma/datamodel.prisma, backend/prisma/generated/prisma-client/index.d.ts, backend/prisma/generated/prisma-client/prisma-schema.js
Updated the prisma user data model
=> update user data model

frontend/pages/test.js, frontend/services/config.js
Used Apollo Client to query data from yoga and display on react client.
https://trello.com/c/92SRC3lx/56-display-data-from-yoga-server-on-frontend-using-apollo-client
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Connected frontend and backend using Apollo Client

frontend/now.json, frontend/pages/test.js
example form for using mutations and local state
=> form example for mutations to add user

.env, backend/resolvers/Mutation.js, backend/schema.graphql
Adds new mutations for deleteUser, createCountry. updateUser works, createVisit (commented out) is in progress.
https://trello.com/c/RHvdduLp/42-yoga-resolvers-queries-and-mutations-included
- [ X] Complete, tested, ready to review and merge
=> Mutation dev

backend/resolvers/Mutation.js, backend/schema.graphql
Finished remaining mutations outlined on our Trello board:
- updateVisit
- deleteVisit
- deleteFriend
https://trello.com/c/RHvdduLp/42-yoga-resolvers-queries-and-mutations-included
=> Finished Remaining Foreseeable Mutations

backend/resolvers/Query.js, backend/schema.graphql
Added query for friends which takes the user's id and returns an array of whatever friend data (including visits) is requested
=> Friends Query

PULL_REQUEST_TEMPLATE.md
Added a Trello link scaffold right below the description in the PULL_REQUEST_TEMPLATE.md. An update for our convenience.
=> Update PULL_REQUEST_TEMPLATE.md to include a link for Trello cards

frontend/next.config.js
https://trello.com/c/tmwTEvYo/85-fix-now-deployment-with-less
fixed less import so less only runs during the build phase
=> fixed less loading issue

frontend/components/Map/Map.js, frontend/components/Map/countryStyles.js, frontend/components/Map/dummyData.js, frontend/components/Map/mapHelpers.js
https://trello.com/c/xZFnXW7Y/84-fix-map-logic-for-border-color-render
https://trello.com/c/WBS75awY/74-map-view-different-colors-of-geojson-from-visit-level
Abstracted logic out of the map component so that the component itself is easier to read and modify. Added helper functions and a style object file for easy access and updates. updated the render logic for borders to accommodate the shape of the data in our database
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Kyranmccann map

frontend/components/Map/countryStyles.js, frontend/components/Map/dummyData.js, frontend/components/Map/mapHelpers.js
=> updating export statements to conform to standards

frontend/services/mutations.js, frontend/services/queries.js
Added to services/mutations.js
- UPDATEUSER_MUTATION,
- DELETEUSER_MUTATION, 
- CREATEVISIT_MUTATION,
- UPDATEVISIT_MUTATION,
- DELETEVISIT_MUTATION,
- ADDFRIEND_MUTATION,
- DELETEFRIEND_MUTATION 
https://trello.com/c/LyKsKyeu/86-abstract-queries-mutations
=> Translated exisiting prisma mutations for apollo on frontend

frontend/pages/settings.js
=> Fix import for settings component [1]

frontend/components/MapHeader/MapDropdown.js, frontend/components/MapHeader/MapIndex.js
[Trello Card](https://trello.com/c/97QGWVh3/93-refactor-map-dropdown-fix-routes-to-use-next-link-update-logout-to-logout-of-oauth)
Refactor MapDropdown into it's own component. Fixed dropdown links to use next/link instead of regular hrefs. Logout is now properly logging out by hitting the backend/api/logout route, which redirects the user back to the landing page.
Tested backend/api/current_user to double check that the user has indeed logged out.
=> MapDropdown Update

frontend/components/Profile/FriendsList.js, frontend/components/Profile/UserCard.js, frontend/components/Profile/UsersDropdown.js, frontend/components/Profile/profile.less, frontend/pages/profile.js
[Trello Card](https://trello.com/c/vZvpooIR/107-profile-page-fix-styling-make-responsive)
removed all inline styling from profile page, made components responsive to screen size
=> Profile design - responsive

frontend/components/Landing/Login/Login.js, frontend/components/Landing/landing.less, frontend/components/Landing/landingPage.js, frontend/components/Profile/FriendsList.js, frontend/components/Profile/UserCard.js, frontend/components/Profile/UsersDropdown.js, frontend/components/Profile/profile.less, frontend/pages/profile.js
[Trello Card](https://trello.com/c/AhQVRHWS/109-landing-page-responsive)
change classNames to follow style guidelines, add media queries for responsiveness
=> Landing page - Responsiveness

frontend/components/CountryViewModal/FriendsVisits.js, frontend/components/CountryViewModal/countryModal.less, frontend/components/Landing/landingPage.js, frontend/components/Map/StaticMap.js, frontend/components/Map/countryStyles.js, frontend/components/Map/map.less, frontend/components/MapHeader/NavigationDropdown.js, frontend/components/MapHeader/mapHeader.less, frontend/components/Profile/profile.less
Newer! Smaller! A little pointier! Also updated the color filled svgs to have a border because no border was unsettling with multiple countries colored in. 
=> New Countries.geojson

frontend/services/Authentication/CurrentUser.js
[Trello Card](https://trello.com/c/A2z64rgP/118-missing-field-user-id-in)
This fix gets rid of the minor warning when the CurrentUser component is making an Axios-GET request to an empty endpoint (when the user is not logged in with Twitter), which was coming back as undefined and being written to the cache.
The change:
```
const fetchUser = async client => {
const res = await axios.get(`${URL}/api/current_user`)
client.writeData({ data: { userId: res.data.id } })
}
```
⬇️
```
const fetchUser = async client => {
const res = await axios.get(`${URL}/api/current_user`);
if (res.data.id !== undefined) {
client.writeData({ data: { userId: res.data.id } });
}
};
```
Fixes # (issue #103)
=> Add If statement to get rid of minor warning

README.md
[Trello Card](https://trello.com/c/x5rlbAGW/13-readme)
Update to Read.ME to include current working tech-stack
=> tech stack READ.ME

frontend/components/Scratcher/index.js
Fixes #107
Our project isn't configured to use automated testing.
=> Resolve issue 107

frontend/components/Friends/addFriend.js, frontend/components/Friends/deleteFriend.js, frontend/components/Friends/friendsCard.js, frontend/components/Profile/FriendsList.js, frontend/components/Profile/UsersDropdown.js, frontend/components/Profile/profile.less, frontend/package.json, frontend/pages/friends.js, frontend/services/routes.js, frontend/yarn.lock
[Trello Card](https://trello.com/c/6f1ae9Tc/121-friend-profile-page-clicking-on-a-user-will-route-to-their-profile-page-where-you-can-now-add-them-as-a-friend)
routes to a users page, conditionally renders if it should display button to add as a friend or remove as a friend. Push for update to master
=> Friends profile

frontend/components/Friends/addFriend.js, frontend/components/Friends/deleteFriend.js, frontend/components/Friends/friendsCard.js, frontend/components/Profile/FriendsList.js, frontend/components/Profile/UsersDropdown.js, frontend/pages/friends.js, frontend/services/requests/profile.js, frontend/services/resolvers.js
- added client mutation to set friend id on dropdown or friend's list
- added query for friend card for retrieval of friend info
- addFriend and deleteFriend buttons have an update on their mutation so friend's list stays up-to-dat
[Trello Card](https://trello.com/c/i4lYkqOw/122-update-on-deletefriend-and-addfriend)
=> Patched up Friend Profile Card

backend/index.js, backend/services/middleware.js, backend/services/passport/constants.js, backend/services/passport/passport.js, backend/services/passport/routes.js
Refactor, comment, and document Twitter authentication process.
Our project isn't configured to use automated testing.
=> Jacob passport

backend/index.js, backend/prisma/datamodel.prisma, backend/prisma/generated/prisma-client/index.d.ts, backend/prisma/generated/prisma-client/prisma-schema.js, backend/resolvers/Mutation.js, backend/resolvers/User.js, backend/schema.graphql, frontend/components/Friends/friendsCard.js, frontend/services/config.js, frontend/services/requests/profile.js
[Trello Card](https://trello.com/c/hR6oVOOA/125-friend-profile-page-add-bio-to-database-create-mutation)
Added bio to prisma datamodel, added bio mutation, update schema and user
=> add bio to datamodel, mutation, schema, user

backend/index.js, backend/prisma/datamodel.prisma, backend/prisma/generated/prisma-client/index.d.ts, backend/prisma/generated/prisma-client/prisma-schema.js, backend/resolvers/Mutation.js, backend/resolvers/User.js, backend/schema.graphql, frontend/components/Friends/friendsCard.js, frontend/services/config.js, frontend/services/requests/profile.js
Reverts Lambda-School-Labs/labs9-map-scratcher#117
=> Revert "add bio to datamodel, mutation, schema, user"

backend/index.js, backend/prisma/datamodel.prisma, backend/prisma/generated/prisma-client/index.d.ts, backend/prisma/generated/prisma-client/prisma-schema.js, backend/resolvers/Mutation.js, backend/resolvers/User.js, backend/schema.graphql, frontend/components/Friends/friendsCard.js, frontend/services/createApolloClient.js, frontend/services/requests/profile.js, frontend/services/routes.js
[Trello Card](https://trello.com/c/TWja0ZYD/124-friend-profile-page-connect-bio-to-user-profile)
added all changes that got reverted in the last PR back, user bio will now display their bio if they have one, otherwise it will just be null
=> reverted changes update, bio now displays if available

backend/services/passport/passport.js, backend/services/passport/routes.js, frontend/package.json, frontend/pages/_app.js, frontend/pages/profile.js, frontend/pages/travels.js, frontend/services/Authentication/CurrentUser.js, frontend/yarn.lock
Reverts Lambda-School-Labs/labs9-map-scratcher#131
=> Revert "Implement getInitialProps for profile page"

frontend/components/CountryModal/countryModal.less, frontend/components/Profile/profile.less
* Fixed profile less (cards at time)
* Fixed modal width
=> Fix styles

frontend/components/Scratcher/utilities.js
Reverts Lambda-School-Labs/labs9-map-scratcher#140
=> Revert "Fix bug whereby scratcher wouldn't scratch"

README.md
Add's profile pictures to read.me, sourced from github
=> Add pictures to read.me

frontend/src/components/CountryModal/FriendsVisits.js
=> fix icon render in friends list

.gitignore, frontend/src/components/CountryModal/FriendsVisits.js, frontend/src/components/CountryModal/ScratchHandler.js, frontend/src/components/Friends/AddFriendButton.js, frontend/src/components/Friends/DeleteFriendButton.js, frontend/src/components/Friends/FriendCard.js, frontend/src/components/Map/mapHelpers.js, frontend/src/pages/friends.js, frontend/src/services/resolvers.js
I removed some variables we were no longer using from several files, so as to remove all the various warnings React was sending to the console.
I also deleted some "a" elements surrounding buttons in the friend card, as React wouldn't let me resolve the issue otherwise. The elements had no href, and may have been there for styling reasons, but I saw no difference in appearance after removing them.
Our project isn't setup to use automated testing.
=> Remove warnings for unused identifiers

frontend/src/components/Friends/AddFriendButton.js, frontend/src/components/Friends/DeleteFriendButton.js, frontend/src/components/Friends/FriendCard.js, frontend/src/components/ProfileHeader/UserDropdown.js, frontend/src/pages/friends.js, frontend/src/services/requests/profile.js
=> Friend Card Buttons Updating

frontend/src/App.js, frontend/src/components/AlpacaFacts/AlpacaFacts.js, frontend/src/components/AlpacaFacts/alpaca-facts.scss, frontend/src/components/Landing/landing.scss, frontend/src/components/Profile/profile.scss, frontend/src/sass/global_theme.scss, frontend/src/sass/index.scss
https://trello.com/c/KGqzlUcG/176-replace-callback-component-with-alpaca-facts
I replaced the "callback component", which displayed a loading spinner and the text "Authenticating..." with an AlpacaFacts component. The AlpacaFacts component selects from an array of (currently 4) comical fictional "facts" about Alpacas, and displays it with the text "Did you know?" beside an image of an Alpaca.
I also refactored some of the SCSS to use a variable for the Corporate blue color used throughout the site. The color is now called "$color-primary", though the variable declaration exists in multiple files and would need to be edited in all locations in order to change the color everywhere.
Our project isn't configured to use automated testing.
=> Alpaca facts

frontend/package.json, frontend/src/components/Friends/FriendCard.js, frontend/src/components/Profile/VisitsChart.js, frontend/src/pages/profile.js, frontend/src/services/requests/profile.js, frontend/yarn.lock
* Added a pie chart on user profile that displays the distribution of your visits by level
* Requires "recharts" dependency
* Colors can be easily changed in VisitsChart component
* Please note that "level" was added to the returned visit object on QUERY_ME_PROFILE
* Getting a failed prop type error (non-breaking) that will have to wait until morning
[Trello Card](https://trello.com/c/VQ7ixAXW/171-visit-level-graphic)
=> Visit Distribution Pie Chart

frontend/src/components/CountryModal/ClearVisitButton.js
Clear visit button in modal now allows the map to update.
=> updated clear visit mutation update logic

frontend/src/components/CountryModal/CountryModal.js, frontend/src/components/CountryModal/DisabledNote.js, frontend/src/components/CountryModal/FriendsVisits.js, frontend/src/components/CountryModal/Header.js, frontend/src/components/CountryModal/UpdateNote.js, frontend/src/components/CountryModal/countryModal.scss
Modal! Now with tabs!
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Tabbed Modal

frontend/src/components/CountryModal/ScratchHandler.js, frontend/src/components/CountryModal/countryModal.scss, frontend/src/components/CountryModal/scratch-handler.scss, frontend/src/components/Map/countryStyles.js, frontend/src/components/MapLegend/Legend.js, frontend/src/components/MapLegend/legend.scss
updates the display of the slider on the modal and the tabs in the header of the modal
=> update modal slider display

frontend/src/components/CountryModal/ScratchHandler.js, frontend/src/components/CountryModal/scratch-handler.scss, frontend/src/components/Scratcher/coin.js, frontend/src/components/Scratcher/index.js, frontend/src/components/Scratcher/scratcher.scss, frontend/src/components/Scratcher/utilities.js
I added a coin scratching animation, as per the spec.
I also decoupled the display and styling of the slider from the scratcher.
Our project isn't configured to use automated testing.
=> Backscratcher

frontend/src/App.js
https://trello.com/c/rlWySvxS/82-sessions-isloggedin-prevents-users-from-viewing-links-when-not-logged-in
I added a function to App.js which checks if the user is logged in. If they are, it allows rendering to continue on a route. If not, the user is redirected to the landing page.
Fixes #149
=> Redirect users from internals routes if no valid token present

frontend/src/components/AlpacaFacts/AlpacaFacts.js, frontend/src/components/MapLegend/Legend.js
Code follows the style guidelines of this project
=> Fixed Map Theme Buttons

frontend/src/components/Profile/VisitsChart.js, frontend/src/components/Profile/profile.scss, frontend/src/sass/global_theme.scss
=> Fixed Profile Responsivity

.netlify/state.json, backend/index.js, frontend/src/components/AlpacaFacts/alpaca-facts.scss, frontend/src/components/CountryModal/ClearVisitButton.js, frontend/src/components/CountryModal/CountryModal.js, frontend/src/components/CountryModal/ScratchHandler.js, frontend/src/components/CountryModal/countryModal.scss, frontend/src/components/CountryModal/scratch-handler.scss, frontend/src/components/MapHeader/mapHeader.scss, frontend/src/components/Profile/profile.scss, frontend/src/services/auth/auth0-variables.js, netlify.toml
Styles:
* Clear visit button no longer interferes with slider at certain breakpoints
* Clear visit button is the right red ($color-danger)
* Modal has a max-width (40% seemed too wide on my biggest monitor)
* Instead of top, middle, and bottom content (legacy from old modal layout) there is just a content div
* Gave modal 1100 z-index so it covers the leaflet zoom buttons which have a 1000 z-index
* Fixed mobile map header margins so it doesn't interfere with the zoom buttons
* Removed interfering legacy friends list break point
* Made alpaca facts font color light for consistency/readability
Deployment:
* Added netlify toml and whitelisted new domain
=> Improvements to responsive styles
